package model.pojo;
// Generated Aug 6, 2014 2:39:16 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String text;
     private String profileImageUrl;
     private Date createdAt;
     private Date modifiedAt;

    public Posts() {
    }

    public Posts(String name, String text, String profileImageUrl, Date createdAt, Date modifiedAt) {
       this.name = name;
       this.text = text;
       this.profileImageUrl = profileImageUrl;
       this.createdAt = createdAt;
       this.modifiedAt = modifiedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getProfileImageUrl() {
        return this.profileImageUrl;
    }
    
    public void setProfileImageUrl(String profileImageUrl) {
        this.profileImageUrl = profileImageUrl;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getModifiedAt() {
        return this.modifiedAt;
    }
    
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }




}


